on: [push]

jobs:
  lint_job:
    runs-on: ubuntu-latest
    name: Linting job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Linting step
        uses: arthrp/FSharpLintAction@v1
        id: fsharplint
        with:
          lint-filepath: FSharpFibonacci/Program.fs